<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="practica2" nsURI="http://practica2/1.0" nsPrefix="practica2">
  <eClassifiers xsi:type="ecore:EClass" name="Clase">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Atributos" upperBound="-1"
        eType="#//Atributo" containment="true" eOpposite="#//Atributo/Clase"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Atributos" upperBound="-1"
        eType="#//Atributo" containment="true" eOpposite="#//Atributo/Clase.1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Relaciones" upperBound="-1"
        eType="#//Relacion.1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Padre" eType="#//Clase"
        eOpposite="#//Clase/Hijo"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Hijo" upperBound="-1" eType="#//Clase"
        eOpposite="#//Clase/Padre"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Atributo">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Clase" lowerBound="1" eType="#//Clase"
        eOpposite="#//Clase/Atributos"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Tipo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Clase" lowerBound="1" eType="#//Clase"
        eOpposite="#//Clase/Atributos.1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Relacion"/>
  <eClassifiers xsi:type="ecore:EClass" name="Relacion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Cardinalidad_1_minima"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Tipo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Clases" lowerBound="2"
        upperBound="2" eType="#//Clase"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="" lowerBound="1" eType="#//Clase"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Cardinalidad_1_maxima"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Cardinalidad_2_minima"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Cardinalidad_2_maxima"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Clase 1" lowerBound="1"
        eType="#//Clase"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Clase 2" lowerBound="1"
        eType="#//Clase"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Herencia">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Padre" lowerBound="1" eType="#//Clase"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Hijo" lowerBound="1" eType="#//Clase"/>
  </eClassifiers>
</ecore:EPackage>
